name: CI Pipeline for Node App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run app build (if needed)
      run: echo "No build step for now"

    - name: Docker build
      run: docker build -t my-node-app .
